server:
  port: 8081
security:
  oauth2:
    server:
      domain: http://localhost:8080
    client:
      client-id: resource-01
      client-secret: user
      access-token-uri: ${security.oauth2.server.domain}/oauth/token
      user-authorization-uri: ${security.oauth2.server.domain}/oauth/authorize
    resource:
      token-info-uri: ${security.oauth2.server.domain}/oauth/check_token
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 6
    host: localhost
    port: 6379
    password: test1234
    timeout: 6000
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
logging:
  level:
    org:
      springframework:
        security: DEBUG